## Рабочая тетрадь

## Задача 1.3.1

In [1]:
import numpy as np
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Задача 1.3.2

In [2]:
q = np.zeros((5, 5))
q[:,:] = np.arange(0, 5)
print(q)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Задача 1.3.3

In [22]:
a = np.random.random((3, 3, 3))
print(a)

[[[0.91343143 0.34211132 0.73989479]
  [0.94911539 0.87860937 0.92951523]
  [0.08068311 0.26997201 0.78062273]]

 [[0.41449839 0.28172459 0.3315978 ]
  [0.17978693 0.98129009 0.94295779]
  [0.20467823 0.08984542 0.41313585]]

 [[0.65025771 0.35742377 0.10213379]
  [0.99384727 0.58383855 0.03410841]
  [0.33485342 0.67980107 0.24571857]]]


## Задача 1.3.4

In [4]:
a = np.ones((5,5))
a[1:4, 1:4] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Задача 1.3.5

In [5]:
a = np.random.random(5)
a = sorted(a)[::-1]
print(a)

[0.7887435042394362, 0.7633613428250071, 0.7473650458284099, 0.6211944271358755, 0.2355146805166629]


## Задача 1.3.6

In [6]:
a = np.array([[1, 3, 6], [1, 5, 3], [1 ,3, 2], [1, 5, 5]])
print(a.shape, a.ndim, sep=', ')

(4, 3), 2


## Задача 2.3.1

In [7]:
import pandas as pd
from math import sqrt
a = pd.Series([5, 5, 4])
b = pd.Series([1, 3, 8])
print(sqrt(sum((b - a)**2)))

6.0


## Задача 2.3.2 - 2.3.3

In [21]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/baby_names_2000.csv'
df = pd.read_csv(url)

In [9]:
df.head()

year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

In [10]:
df.head()

year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

In [11]:
df.shape

(624236, 4)

In [12]:
df.describe()

year          count
count  624236.000000  624236.000000
mean     2009.115961     113.971929
std         5.383550     754.696900
min      2000.000000       5.000000
25%      2005.000000       7.000000
50%      2009.000000      11.000000
75%      2014.000000      29.000000
max      2018.000000   34477.000000

In [13]:
df.iloc[1:10,[1, 2]]

name gender
1     Hannah      F
2    Madison      F
3     Ashley      F
4      Sarah      F
5     Alexis      F
6   Samantha      F
7    Jessica      F
8  Elizabeth      F
9     Taylor      F

In [14]:
df[df['name'] == 'Tyler'].head()

year   name gender  count
415    2000  Tyler      F    683
17664  2000  Tyler      M  21504
30262  2001  Tyler      F    569
47757  2001  Tyler      M  19273
60570  2002  Tyler      F    523

## Задача 3.3.2

In [25]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# Загрузка данных
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
data = pd.read_csv(url)
# Нормализация первого числового признака с использованием минимаксного преобразования
scaler = MinMaxScaler()
data['sepal_length_cm'] = scaler.fit_transform(data[['sepal_length_cm']])
# Нормализация второго числового признака с использованием z-масштабирования
scaler = StandardScaler()
data['sepal_width_cm'] = scaler.fit_transform(data[['sepal_width_cm']])
# Просмотр первых 5 строк нормализованных данных
print(data.head())




   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa


# Пример 1.2.1

In [7]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# Пример 1.2.2

In [8]:
a = np.zeros(10) # Создать вектор (одномерный массив) размера 10, заполненный нулями
b = np.ones(10) # Создать вектор размера 10, заполненный единицами
c = np.full(10, 5) # Создать вектор размера 10, заполненный заданным числом
d = np.arange(10, 20) # Создать вектор со значениями от 10 до 19 # arrange не найден?
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


# Пример 1.2.3

In [9]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.001905259938966064 0.9929851930697332 0.5241949083836355


# Пример 1.2.4

In [10]:
A = np.arange(25).reshape(5,5) # arrange не найден?
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# Пример 1.2.5

In [11]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# Пример 1.2.6

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# Пример 2.2.1

In [13]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


# Пример 2.2.2

In [14]:
s1 = pd.Series([1,2,3,4,5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# Пример 2.2.3

In [15]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# Пример 2.2.4

In [16]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# Пример 2.2.5

In [17]:
dataframe.head(2) # взглянуть на первые несколько строк
dataframe.tail(3) # последние строки
dataframe.shape # кол-во строк и столбцов
dataframe.describe() # описательная статистика для любых числовых столбц

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# Пример 2.2.6

In [18]:
dataframe.iloc[1:4] # для выбора 1 или нескольких строк, либо значений 

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# Пример 2.2.7

In [19]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# Пример 3.2.1

In [20]:
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# Пример 3.2.2

In [5]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

# Мы можем увидеть эффект стандартизации, обратившись к среднему значению и стандартному отклонению результата нашего решения
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


# Пример 3.2.3

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small